### ISSUE TITLE
Can I translate your article "Cuda, TensorFlow and capsule networks"?

### ISSUE THREAD

**Issue by weakish** [jostosh/jostosh.github.io#2]
Hi, I'd like to translate the cool article "Cuda, TensorFlow and capsule networks" into Chinese.
I noticed that this repository is licensed under MIT,
but I am not sure whether posts are also licensed under MIT
or just the website code is under MIT?

If posts are not under MIT, can you give the permission to translate and publish the article
on https://www.jqr.com/ai/
(The translated text will also be published on some corresponding accounts on Chinese social networks.)

Thanks.

**Comment by jostosh** [comment]
Thanks for your interest! Yes, you can translate it!

**Comment by weakish** [comment]
Just finished the translation: https://www.jqr.com/article/000055

Credit is given at the beginning (in a translator's note)
and the original post is linked back in the end.
If you have any other requirements or suggestions, please inform me.

Possible typos encountered during translation:

> have a look at __the article__

__the article__ linked to this post itself

> we have __the__ sum the gradients for each weight over all samples in the batch

to

**Comment by jostosh** [comment]
Thanks for pointing out the typos! I've updated the post and added a link to your translation.
