### ISSUE TITLE
nvcc compile

### ISSUE THREAD

**Issue by hassanisaadi** [jostosh/jostosh.github.io#3]
Hi, 
Thanks for your perfect way of describing your new capsnet and adding it to the TF as a GPU supported op. I wish you released how did you compile your source code.

Can you give us a hint? Or adding a new cmake/bash script file to compile would be great.

Thanks

**Comment by jostosh** [comment]
Hi, thanks for reading! Did you try [this file](https://github.com/jostosh/capsnet/blob/master/ops/compile.sh) already?

**Comment by hassanisaadi** [comment]
Oh, missed that. Thanks.
